services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - db
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DEBUG: ${DEBUG}
            DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
            DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
            DATABASE_ENGINE: ${DATABASE_ENGINE}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}

    db:
        image: postgres:17
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        env_file:
            - .env

volumes:
    postgres_data:
