services:
    django-website:
        image: django-website
        container_name: django-docker
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8000:8000
        env_file:
            - .env
