# Generated by Django 5.2.3 on 2025-06-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='apis.specialization'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
