# Generated by Django 5.2.3 on 2025-06-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_doctor_is_active_alter_doctor_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='apis.specialization'),
        ),
    ]
