# Generated by Django 5.2.3 on 2025-06-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_doctor_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='tags',
            new_name='specializations',
        ),
    ]
